global:
  scrape_interval: 10s

scrape_configs:
  - job_name: flask-app
    static_configs:
      - targets:
          - honeypot-backend:5000

  - job_name: "honeypot-bait"
    static_configs:
      - targets: ["honeypot-bait:3000"]

  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: redpanda
    static_configs:
      - targets:
          - redpanda:9644
    metrics_path: /public_metrics
