{
 "title": "Honeypod-backend SERVER",
 "tags": [ "honeypot-backend" ],
 "time": { "from": "2025-04-26T09:35:21.270Z", "to": "2025-04-26T21:35:21.270Z" },
 "panels": [
  {
   "title": "CPU и Загрузка",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage: honeypod-backend SERVER",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage_Kbytes{instance=\"honeypot-backend:5000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее время запроса,",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m])) / sum(rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}